In [ ]:
# Hebbian Learning Algorithm Implementation
import numpy as np

# Define input patterns (including bias term)
X = np.array([
    [1, 0, 0],   # bias + inputs
    [1, 0, 1],
    [1, 1, 0],
    [1, 1, 1]
])

# Target outputs for AND logic
Y = np.array([[0], [0], [0], [1]])

# Initialize weights
W = np.zeros((3, 1))
learning_rate = 1

print("Initial Weights:\n", W)
print("--------------------------------------------------")

# Hebbian Learning Rule
for epoch in range(len(X)):
    x = X[epoch].reshape(3, 1)
    y = Y[epoch][0]

    # Weight update rule: ΔW = η * x * y
    dW = learning_rate * x * y
    W += dW

    print(f"Iteration {epoch+1}:")
    print("Input:", X[epoch])
    print("Target:", y)
    print("ΔW:\n", dW)
    print("Updated Weights:\n", W)
    print("--------------------------------------------------")

# Testing
print("Final Weights:\n", W)
print("--------------------------------------------------")

# Compute output using learned weights
def activation(net):
    return 1 if net >= 0 else 0

print("Testing learned weights:")
for i in range(len(X)):
    net_input = np.dot(X[i], W)
    output = activation(net_input)
    print(f"Input: {X[i][1:]}, Output: {output}")


Initial Weights:
 [[0.]
 [0.]
 [0.]]
--------------------------------------------------
Iteration 1:
Input: [1 0 0]
Target: 0
ΔW:
 [[0]
 [0]
 [0]]
Updated Weights:
 [[0.]
 [0.]
 [0.]]
--------------------------------------------------
Iteration 2:
Input: [1 0 1]
Target: 0
ΔW:
 [[0]
 [0]
 [0]]
Updated Weights:
 [[0.]
 [0.]
 [0.]]
--------------------------------------------------
Iteration 3:
Input: [1 1 0]
Target: 0
ΔW:
 [[0]
 [0]
 [0]]
Updated Weights:
 [[0.]
 [0.]
 [0.]]
--------------------------------------------------
Iteration 4:
Input: [1 1 1]
Target: 1
ΔW:
 [[1]
 [1]
 [1]]
Updated Weights:
 [[1.]
 [1.]
 [1.]]
--------------------------------------------------
Final Weights:
 [[1.]
 [1.]
 [1.]]
--------------------------------------------------
Testing learned weights:
Input: [0 0], Output: 1
Input: [0 1], Output: 1
Input: [1 0], Output: 1
Input: [1 1], Output: 1
